import {
  DarkTheme as DefaultDarkTheme,
  DefaultTheme as DefaultLightTheme,
} from "@react-navigation/native";
import {
  DarkTheme as DarkThemeType,
  LightTheme as LightThemeType,
} from "./types";

export const Colors = {
  secondaryAccent: "rgba(0, 190, 150, 1)",
  light: {
    primary: "#6D5E0F",
    surfaceTint: "#6D5E0F",
    onPrimary: "#FFFFFF",
    primaryContainer: "#F7E388",
    onPrimaryContainer: "#534600",
    secondary: "#665E40",
    onSecondary: "#FFFFFF",
    secondaryContainer: "#EDE2BC",
    onSecondaryContainer: "#4D472B",
    tertiary: "#43664F",
    onTertiary: "#FFFFFF",
    tertiaryContainer: "#C4ECCF",
    onTertiaryContainer: "#2B4E38",
    error: "#BA1A1A",
    onError: "#FFFFFF",
    errorContainer: "#FFDAD6",
    onErrorContainer: "#93000A",
    background: "#FFF9ED",
    onBackground: "#1E1C13",
    surface: "#FFF9ED",
    onSurface: "#1E1C13",
    surfaceVariant: "#E9E2D0",
    onSurfaceVariant: "#4B4739",
    outline: "#7C7768",
    outlineVariant: "#CDC6B4",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#333027",
    inverseOnSurface: "#F7F0E2",
    inversePrimary: "#DAC76F",
    text: "#1E1C13",
    textTint: "#4B4739",
  },
  dark: {
    primary: "#DAC76F",
    surfaceTint: "#DAC76F",
    onPrimary: "#393000",
    primaryContainer: "#534600",
    onPrimaryContainer: "#F7E388",
    secondary: "#D1C6A2",
    onSecondary: "#363016",
    secondaryContainer: "#4D472B",
    onSecondaryContainer: "#EDE2BC",
    tertiary: "#A9D0B4",
    onTertiary: "#143723",
    tertiaryContainer: "#2B4E38",
    onTertiaryContainer: "#C4ECCF",
    error: "#FFB4AB",
    onError: "#690005",
    errorContainer: "#93000A",
    onErrorContainer: "#FFDAD6",
    background: "#15130B",
    onBackground: "#E8E2D4",
    surface: "#15130B",
    onSurface: "#E8E2D4",
    surfaceVariant: "#4B4739",
    onSurfaceVariant: "#CDC6B4",
    outline: "#969080",
    outlineVariant: "#4B4739",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#E8E2D4",
    inverseOnSurface: "#333027",
    inversePrimary: "#6D5E0F",
    text: "#E8E2D4",
    textTint: "#CDC6B4",
  },
};

export const LightTheme = {
  ...DefaultLightTheme,
  ...Colors.light,
  colors: {
    primary: Colors.light.primary,
    background: Colors.light.background,
    card: Colors.light.surface,
    text: Colors.light.onBackground,
    border: Colors.light.outline,
    notification: Colors.secondaryAccent,
  },
} as LightThemeType;

export const DarkTheme = {
  ...DefaultDarkTheme,
  ...Colors.dark,
  colors: {
    primary: Colors.dark.primary,
    background: Colors.dark.background,
    card: Colors.dark.surface,
    text: Colors.dark.onBackground,
    border: Colors.dark.outline,
    notification: Colors.secondaryAccent,
  },
} as DarkThemeType;
